import { Emotion } from '../../src/diary/entities/emotion.entity';
import { DataSource } from 'typeorm';

export const emotionSeeds = [
  {
    id: 1,
    name: '정말 행복해요',
    code: 'overjoyed',
    order: 1,
    parent_id: null,
    image_url: '',
  },
  {
    id: 2,
    name: '즐거워요',
    code: 'good',
    order: 2,
    parent_id: null,
    image_url: '',
  },
  {
    id: 3,
    name: '보통이에요',
    code: 'neutral',
    order: 3,
    parent_id: null,
    image_url: '',
  },
  {
    id: 4,
    name: '슬퍼요',
    code: 'sad',
    order: 4,
    parent_id: null,
    image_url: '',
  },
  {
    id: 5,
    name: '정말 우울해요',
    code: 'devastated',
    order: 5,
    parent_id: null,
    image_url: '',
  },
  {
    id: 6,
    name: '기분이 최고예요!',
    code: 'null',
    order: 101,
    parent_id: 1,
    image_url: '',
  },
  {
    id: 7,
    name: '사랑받는 느낌이에요',
    code: 'null',
    order: 102,
    parent_id: 1,
    image_url: '',
  },
  {
    id: 8,
    name: '신나요',
    code: 'null',
    order: 103,
    parent_id: 1,
    image_url: '',
  },
  {
    id: 9,
    name: '활력이 넘쳐요',
    code: 'null',
    order: 104,
    parent_id: 1,
    image_url: '',
  },
  {
    id: 10,
    name: '성취감을 느껴요',
    code: 'null',
    order: 105,
    parent_id: 1,
    image_url: '',
  },
  {
    id: 11,
    name: '편안해요',
    code: 'null',
    order: 201,
    parent_id: 2,
    image_url: '',
  },
  {
    id: 12,
    name: '뿌듯해요',
    code: 'null',
    order: 202,
    parent_id: 2,
    image_url: '',
  },
  {
    id: 13,
    name: '기대돼요',
    code: 'null',
    order: 203,
    parent_id: 2,
    image_url: '',
  },
  {
    id: 14,
    name: '감사해요',
    code: 'null',
    order: 204,
    parent_id: 2,
    image_url: '',
  },
  {
    id: 15,
    name: '여유로워요',
    code: 'null',
    order: 205,
    parent_id: 2,
    image_url: '',
  },
  {
    id: 16,
    name: '그냥 그래요',
    code: 'null',
    order: 301,
    parent_id: 3,
    image_url: '',
  },
  {
    id: 17,
    name: '차분해요',
    code: 'null',
    order: 302,
    parent_id: 3,
    image_url: '',
  },
  {
    id: 18,
    name: '무덤덤해요',
    code: 'null',
    order: 303,
    parent_id: 3,
    image_url: '',
  },
  {
    id: 19,
    name: '감정 변화가 없어요',
    code: 'null',
    order: 304,
    parent_id: 3,
    image_url: '',
  },
  {
    id: 20,
    name: '피곤해요',
    code: 'null',
    order: 401,
    parent_id: 4,
    image_url: '',
  },
  {
    id: 21,
    name: '스트레스 받아요',
    code: 'null',
    order: 402,
    parent_id: 4,
    image_url: '',
  },
  {
    id: 22,
    name: '걱정돼요',
    code: 'null',
    order: 403,
    parent_id: 4,
    image_url: '',
  },
  {
    id: 23,
    name: '짜증나요',
    code: 'null',
    order: 404,
    parent_id: 4,
    image_url: '',
  },
  {
    id: 24,
    name: '의욕이 없어요',
    code: 'null',
    order: 405,
    parent_id: 4,
    image_url: '',
  },
  {
    id: 25,
    name: '절망적이에요',
    code: 'null',
    order: 501,
    parent_id: 5,
    image_url: '',
  },
  {
    id: 26,
    name: '무기력해요',
    code: 'null',
    order: 502,
    parent_id: 5,
    image_url: '',
  },
  {
    id: 27,
    name: '외로워요',
    code: 'null',
    order: 503,
    parent_id: 5,
    image_url: '',
  },
  {
    id: 28,
    name: '불안해요',
    code: 'null',
    order: 504,
    parent_id: 5,
    image_url: '',
  },
  {
    id: 29,
    name: '슬퍼요',
    code: 'null',
    order: 505,
    parent_id: 5,
    image_url: '',
  },
];

export async function seedEmotion(dataSource: DataSource) {
  const repository = dataSource.getRepository(Emotion);

  for (const seed of emotionSeeds) {
    const existing = await repository.findOne({ where: { id: seed.id } });
    if (!existing) {
      await repository.save(seed);
    }
  }
}
